// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.RingSizeConverter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("input_diameter_mm")]
        public double InputDiameterMm { get; set; }

        [JsonProperty("circumference_mm")]
        public double CircumferenceMm { get; set; }

        [JsonProperty("conversions")]
        public Conversions Conversions { get; set; }

        [JsonProperty("note")]
        public string Note { get; set; }
    }

    public partial class Conversions
    {
        [JsonProperty("diameter_mm")]
        public double DiameterMm { get; set; }

        [JsonProperty("circumference_mm")]
        public double CircumferenceMm { get; set; }

        [JsonProperty("us")]
        public long Us { get; set; }

        [JsonProperty("uk")]
        public string Uk { get; set; }

        [JsonProperty("eu")]
        public long Eu { get; set; }

        [JsonProperty("jp")]
        public long Jp { get; set; }

        [JsonProperty("ch")]
        public long Ch { get; set; }

        [JsonProperty("au")]
        public string Au { get; set; }
    }
}
